### ISSUE TITLE
SQL error on creating table - notebook part1-load-data.ipynb

### ISSUE THREAD

**Issue by cbtham** [Azure/feast-azure#18]
I've followed the steps at https://github.com/Azure/feast-azure/tree/main/provider/tutorial but couldnt get table for customer data to load. Did a printf and made sure keyvault secret has a value. I am using the one button deploy method (not k8 cluster).

Screenshot:
Error: OperationalError: (pyodbc.OperationalError) ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)') (Background on this error at: https://sqlalche.me/e/14/e3q8)

![image](https://user-images.githubusercontent.com/5702935/141099445-82fac6e8-ca33-4090-9fac-4a4110a85deb.png)

**Comment by samuel100** [comment]
@cbtham thanks for raising! Just to double check had the Synapse workspace and dedicated pool been provisioned?

**Comment by cbtham** [comment]
Yes, it has been already been provisioned, up and running. I initially thought it was a driver version for sql, tried lowering it but no luck. I also double checked keyvault and can confirm the value is there in secret

**Comment by cbtham** [comment]
Managed to overcome the problem. There is an error in the one-click template that uses a static roleDefinitionID parameter. This ID is different for every subscription. To get your own unique one, do "az role definition list -n Contributor" without "" and replace the guid returned into Role Definition Id in the template

**Comment by james-tn** [comment]
I cannot get it working in WestUS2, in Central and changing/not changing the Role Definition Id. What exactly do I need to do?

**Comment by james-tn** [comment]
Same error: OperationalError: (pyodbc.OperationalError) ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
(Background on this error at: https://sqlalche.me/e/14/e3q8)

**Comment by slsu0424** [comment]
@cbtham @samuel100 - I have also run into this same issue as @james-tn.  I have provisioned in East US.  I have changed the Role Definition ID as prescribed above, no resolution.
