### ISSUE TITLE
Issue on loading feast - missing module

### ISSUE THREAD

**Issue by jcordtz** [Azure/feast-azure#22]
In the tutorial - step 2 in notebook 2 "Registre..." fails with missing module. 
The error is triggered by the command "fs = FeatureStore("./feature_repo")"
The Feast evrsion is 0.15.1 and the Azure feast provider is 0.2.1.

Error "snippet" first lines and last line.
ModuleNotFoundError                       Traceback (most recent call last)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/feast/infra/online_stores/redis.py in <module>
     43     from redis import Redis
---> 44     from rediscluster import RedisCluster
.........
FeastModuleImportError: Could not import RedisOnlineStoreConfig module 'feast.infra.online_stores.redis'

**Comment by samuel100** [comment]
@jcordtz thanks for raising! Before the fs =FeatureStore() cell, does the error resolve if you add a new cell and run:

!pip install redis-py-cluster

? The suspicion here is that feast is missing a dependency.

**Comment by samuel100** [comment]
There is a bug in setup.py where there is no comma. Resolving now.
