### ISSUE TITLE
SQL error on creating table - notebook part1-load-data.ipynb

### ISSUE THREAD

**Issue by delta0123** [Azure/feast-azure#35]
I have followed all steps mentioned in https://github.com/Azure/feast-azure/tree/main/provider/tutorial and had even changes roleDefinitionID parameter as per previous defect but still I'm getting same error.
![image](https://user-images.githubusercontent.com/45678064/144553769-474aac12-6173-40ef-8b5c-7d59bd328463.png)

**Comment by cbtham** [comment]
try this
https://github.com/Azure/feast-azure/issues/18

**Comment by delta0123** [comment]
> 

I was not able to install Microsoft authentication which was part of that ARM template can you let me know if that might be the reason for this errror, as I have tried changing  roleDefinitionID parameter

**Comment by cbtham** [comment]
What is the issue with auth? Is it the error that you posted above? if so delete the current deployment, start a new one and change the role id parameter that you retrieve from the command i posted on the other thread. It should solve this error you posted above

**Comment by delta0123** [comment]
Hi @cbtham ,

let me know if we can connect for some time and get the issue resolved.

**Comment by delta0123** [comment]
1.Since this is implemented on an organization subscription I do not have authorization or access to add  Microsoft Authorization , I have checked it with respective team and they had told that Microsoft Authorization cannot be access due to restrictions. 
2.Apart from this I had tried changing Role Definition Id in the template.
Let me know if there is any other way to fix the error as I tried fixing looking for pyodbc.connect but could not find same.

error: 
OperationalError: (pyodbc.OperationalError) ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)') (Background on this error at: https://sqlalche.me/e/14/e3q8)

**Comment by cbtham** [comment]
You'll need auth for sure. I believe this error is showing because SQL pool doesnt have the correct assigned permission. Can you reprovision again the environment(without changing roleId) by selecting other region(different from the one you have now) and see if it works.

I'm using australia east without changing roleId
