### ISSUE TITLE
Error while installing feast SDK - return codecs.charmap_decode(input,self.errors,decoding_table)[0]

### ISSUE THREAD

**Issue by rajendra-tamboli** [Azure/feast-azure#36]
Hi, while trying to run the following command getting codecs error mentioned below. 

pip install "git+https://github.com/Azure/feast-azure.git#subdirectory=cluster/sdk/python"

Error ----------------------------------------------------------------------------------------
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 23, in decode
      return codecs.charmap_decode(input,self.errors,decoding_table)[0]
  UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 819: character maps to <undefined>

**Comment by snowmanmsft** [comment]
Hi - can you try to install using this command with Python 3.8? I just tested it should work:
```
pip install git+https://github.com/xiaoyongzhu/feast-spark.git#subdirectory=python
```
Also I'm trying to fix the above issue. Looks like it's a dependency issue.
