### ISSUE TITLE
feast cluster installation fails with rbac.authorization.k8s.io/v1beta API version (ClusterRole)

### ISSUE THREAD

**Issue by andrijaperovic** [Azure/feast-azure#39]
Following the instructions listed in cluster installation on AKS cluster `v1.22.4`:
https://github.com/Azure/feast-azure/tree/main/cluster/setup

Initial installation steps pass, but api versions are not recognized in newer version of AKS (stable API version `rbac.authorization.k8s.io/v1` should work instead of `rbac.authorization.k8s.io/v1beta1`).

Any change to specify a newer version of helm chart in the installation shell script?

Here is the issue which I encounter:

sudo ./installfeast.sh (parameters passed here)
**INFO: Install feast
error: failed to create secret secrets "feast-postgresql" already exists
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "ClusterRole" in version "rbac.authorization.k8s.io/v1beta1", unable to recognize "": no matches for kind "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1beta1", unable to recognize "": no matches for kind "Role" in version "rbac.authorization.k8s.io/v1beta1", unable to recognize "": no matches for kind "RoleBinding" in version "rbac.authorization.k8s.io/v1beta1"]**

**Comment by andrijaperovic** [comment]
The installation shell script uses a different helm repo than the one which is commonly used:
https://github.com/feast-dev/feast-helm-charts/tree/main#installation

**Comment by rramani** [comment]
Thanks for reporting this. We will look into this and get back to you.

**Comment by andrijaperovic** [comment]
Thank you @rramani . I was able to fix the issue by downloading the helm chart and modifying the APi versions then installing from local copy of my helm chart.

**Comment by jainr** [comment]
Thanks for reporting this @andrijaperovic, I updated the helm chart repo URL to latest one and that fixed the issue on Kubernetes version 1.22.4

INFO: Add feast charts
"feast-charts" already exists with the same configuration, skipping
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "feast-charts" chart repository
Update Complete. ⎈Happy Helming!⎈
INFO: Install feast
secret/feast-postgresql created
NAME: feast-release2
LAST DEPLOYED: Tue Jan 25 14:36:15 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
INFO: Deployment is not finished yet. check again in 30 seconds
INFO: Deployment is not finished yet. check again in 30 seconds
