### ISSUE TITLE
Error - Cannot update to latest feast 0.17

### ISSUE THREAD

**Issue by cbtham** [Azure/feast-azure#40]
Updating to 0.17 with ```pip install --upgrade feast``` fails with error message:

ERROR: feast-azure-provider 0.2.2 has requirement feast[redis]==0.15.1, but you'll have feast 0.17.0 which is incompatible.

Tried modifying setup.py in my own fork with deployment template pointing to my own fork that has ==0.17 specified but still error out.
own fork: https://github.com/cbtham/feast-azure/blob/main/provider/sdk/setup.py

It seems like the source of feast-azure-provider(URL below) needs to be updated to support 0.17 because the current version 0.2.2 hardcoded ==0.15.1

setup
     install_requires=[
        "feast[redis]==0.15.1"

https://pypi.org/project/feast-azure-provider/

**Comment by cbtham** [comment]
Force upgrade will bump feast version to 0.17 but it uninstalls feast-azure-provider in the process. This cause error when using feature store.

FeastModuleImportError: Could not import Provider module 'feast_azure_provider.azure_provider'

**Comment by adchia** [comment]
There weren't any breaking changes for this provider between 0.15.1 and 0.17/0.18, so should be as simple as doing feast[redis] >= 0.15.1

**Comment by cbtham** [comment]
Unfortunately that is not the case. Yes you can do feast[redis] >=0.15.1 and it will go to 0.17 but the setup will soon revert to 0.15.1 with an error feast-azure-provider 0.22 is not compatible with the version 0.17

**Comment by adchia** [comment]
right i meant that the azure provider setup.py should have a more relaxed version for feast
