### ISSUE TITLE
Issue in tutorial code for generating the Azure environment

### ISSUE THREAD

**Issue by jcordtz** [Azure/feast-azure#6]
In the code for creating the blob storage the name includes a "-", this is not an accepted blob storage name.

The code says

**# a blob account name
storageAccountName=_fsblob-$RANDOM_
echo "Variable storageAccountName is set to $storageAccountName"**

It should say

**# a blob account name
storageAccountName=_fsblob$RANDOM_
echo "Variable storageAccountName is set to $storageAccountName"**

**Comment by samuel100** [comment]
Thanks! Fixed in PR https://github.com/Azure/feast-azure/pull/10
